language: node_js
node_js: stable

install:
  - npm i

script:
  - npm run build

after_script:
  - cd docs\.vuepress\dist
  - git init
  - git config user.name "tinymark"
  - git config user.email "bladem@163.com"
  - git add .
  - git commit -m "提交"
  - git push --force --quiet https://${GH_TOKEN}@${GH_REF} master:master

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com:TinyMark/TinyMark.github.io.git